//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Siparis
    {
        public int id { get; set; }
        public string isim { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public string pizzaboy { get; set; }
        public string cesitler { get; set; }
        public string icecek { get; set; }
        public string pizzaturu { get; set; }
        public Nullable<int> pizzadeti { get; set; }
        public string siparistarihi { get; set; }
        public Nullable<bool> promosyon { get; set; }
    }
}
